# Generated by Django 5.0.7 on 2024-07-31 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_alter_user_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment',
            new_name='body',
        ),
    ]
