# Generated by Django 5.0.7 on 2024-08-01 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_comment_blog_alter_comment_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='course',
            field=models.ManyToManyField(null=True, related_name='students', to='course.course'),
        ),
    ]
