# Generated by Django 5.0.7 on 2024-07-30 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0001_initial'),
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.comment'),
        ),
    ]
